### ISSUE TITLE
[Bug] Does not work with `HttpClient.Send`

### ISSUE THREAD

**Issue by ThaDaVos** [thomasgalliker/HttpClient.Caching#15]
### Description
It seems it only works with `HttpClient.SendAsync` the `Send` calls aren't cached - sadly I cannot use the Async calls.

### Steps to Reproduce
1. Use `HttpClient.Send`

### Expected Behavior
- It uses cache

### Actual Behavior
- It does not use cache

### Basic Information
- Version with issue: latest
- Last known good version: none

**Comment by thomasgalliker** [comment]
@ThaDaVos can you please test if the latest 1.5.x nuget works with HttpClient.Send in your software?

**Comment by ThaDaVos** [comment]
It seems to work now - except that I try to check if it's cached by using `GetStatistics` before and after the send call - but both have the exact same statistics - guess it's due to the use of the `ConcurrentDictionary`:
My Code:
```C#
        StatsResult before = CachingStatsProvider?.GetStatistics() ?? new StatsResult("NULL");

        _lastResponse = Client.Send(request);

        StatsResult after = CachingStatsProvider?.GetStatistics() ?? new StatsResult("NULL");
```

Here is uses `values`:
https://github.com/thomasgalliker/HttpClient.Caching/blob/f2831a70b6d896fb54e401110127e05f5c131269/HttpClient.Caching/Abstractions/StatsProvider.cs#L41
Which is a `ConcurrentDictionary`:
https://github.com/thomasgalliker/HttpClient.Caching/blob/f2831a70b6d896fb54e401110127e05f5c131269/HttpClient.Caching/Abstractions/StatsProvider.cs#L13

I checked as follows:
```C#
string cachedStateString = UseCaching && before.Total.CacheHit != after.Total.CacheHit ? $"[CACHED:{before.CacheType}:{after.CacheType}] " : $"[NON-CACHED:{before.CacheType}:{after.CacheType}]";

        Logger.Debug($"HttpClient[{Reference}]{usesCachingString} {cachedStateString}=> Of {before.Total.TotalRequests} requests, {before.Total.CacheHit} were from cache. Now {after.Total.TotalRequests} requests, {after.Total.CacheHit} are from cache");
```

LOG:
```log
2024-06-26 09:07:27.0341 | DEBUG | ACTIVE | HttpClient[SnelStart][C:1] [NON-CACHED:SnelStart:SnelStart]=> Of 5 requests, 3 were from cache. Now 5 requests, 3 are from cache
```

So I guess that results in both being the same
